# Generated by Django 3.1.6 on 2021-04-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('Code_Equip', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Designation', models.CharField(blank=True, max_length=200)),
                ('Date_Ach', models.DateTimeField(auto_now_add=True)),
                ('Date_mise_service', models.DateTimeField(auto_now_add=True)),
                ('Carct_tech', models.CharField(max_length=300)),
                ('Date_fin_garantie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
