# Generated by Django 3.1.6 on 2021-04-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipements',
            options={'ordering': ['Code_Equip']},
        ),
        migrations.AddField(
            model_name='equipements',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipements',
            name='Carct_tech',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='equipements',
            name='Code_Equip',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipements',
            name='Designation',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
