# Generated by Django 3.1.6 on 2021-04-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0004_auto_20210427_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id_intervention', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['id_intervention'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id_panne', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.equipement')),
                ('id_intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.intervention')),
            ],
            options={
                'ordering': ['id_panne'],
            },
        ),
    ]
