# Generated by Django 3.1.6 on 2021-04-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0005_intervention_panne'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiecesR',
            fields=[
                ('id_pieceR', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.fournisseur')),
            ],
            options={
                'ordering': ['id_pieceR'],
            },
        ),
        migrations.CreateModel(
            name='Rechange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.intervention')),
                ('id_pieceR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.piecesr')),
            ],
        ),
    ]
