# Generated by Django 3.1.6 on 2021-04-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_piecesr_rechange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={},
        ),
        migrations.AlterModelOptions(
            name='panne',
            options={},
        ),
        migrations.AlterModelOptions(
            name='piecesr',
            options={},
        ),
    ]
