# Generated by Django 3.1.6 on 2021-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_auto_20210427_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='Designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='Designation_fournisseur',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
