# Generated by Django 3.1.6 on 2021-04-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0009_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='id_equipement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.equipement'),
        ),
    ]
