# Generated by Django 3.1.6 on 2021-04-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0010_auto_20210427_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='Designation_doc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
