# Generated by Django 3.1.6 on 2021-04-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0012_auto_20210428_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id_gamme', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.equipement')),
                ('id_intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.intervention')),
            ],
        ),
    ]
