# Generated by Django 3.1.6 on 2021-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0013_gamme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='id_Document',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Code_Equip',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
