# Generated by Django 3.1.6 on 2021-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0014_auto_20210508_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='id_Document',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
