# Generated by Django 3.1.6 on 2021-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0018_auto_20210508_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='id_Document',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='id_fournisseur',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gamme',
            name='id_gamme',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='id_intervention',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='panne',
            name='id_panne',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='piecesr',
            name='id_pieceR',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
