# Generated by Django 3.1.6 on 2021-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0021_auto_20210508_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piecesr',
            options={'ordering': ['Designation_piece_Rechange']},
        ),
        migrations.AddField(
            model_name='piecesr',
            name='Designation_piece_Rechange',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
