# Generated by Django 3.1.6 on 2021-05-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0022_auto_20210508_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id_Emplacement', models.AutoField(primary_key=True, serialize=False)),
                ('Designation_Emplacement', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamme',
            options={'ordering': ['Designation_Operation']},
        ),
        migrations.AddField(
            model_name='documentation',
            name='Code_Document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='Lien_fichier_joint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamme',
            name='Designation_Operation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipement',
            name='id_Emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.emplacement'),
        ),
    ]
