# Generated by Django 3.1.6 on 2021-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0024_gamme_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamme',
            name='Type_Operation',
            field=models.CharField(choices=[('P', 'Preventive'), ('C', 'Curative'), ('A', 'Ameliorative')], default='P', max_length=2),
        ),
    ]
