# Generated by Django 3.1.6 on 2021-05-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0025_auto_20210508_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emplacement',
            options={'ordering': ['Designation_Emplacement']},
        ),
        migrations.AddField(
            model_name='equipement',
            name='Photo_Equip',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
