# Generated by Django 3.1.6 on 2021-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0026_auto_20210508_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='Photo_Equip',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
