# Generated by Django 3.1.6 on 2021-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0027_auto_20210508_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='Code_Panne',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='Date_H_Min_Declaration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='Declarant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='panne',
            name='Duree_Reelle_Panne',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
