# Generated by Django 3.1.6 on 2021-05-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0029_auto_20210509_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='Adresse_Four',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Civilite',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Code_Fourn',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Contact_principal',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Site_web',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Code_Intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Date_Fin_Reelle_Intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Date_Fin_prevue_Intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Date_deb_Reelle_Intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Date_deb_prevue_Intervention',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Duree_Reelle',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='Duree_prevue',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='Code_Panne',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='Date_H_Min_Declaration',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='Declarant',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='Duree_Reelle_Panne',
        ),
        migrations.RemoveField(
            model_name='piecesr',
            name='Code_Piece',
        ),
        migrations.RemoveField(
            model_name='piecesr',
            name='Quantite_Pieces_rechange',
        ),
    ]
