# Generated by Django 3.1.6 on 2021-05-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0033_remove_gamme_frequence_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decisions_Amelioration',
            fields=[
                ('id_Decisions_Amelioration', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Code_action', models.IntegerField(blank=True, null=True)),
                ('Designation_Action', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_deb', models.DateTimeField(auto_now_add=True, null=True)),
                ('Date_Fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['Designation_Action'],
            },
        ),
        migrations.CreateModel(
            name='Vals_KPIs',
            fields=[
                ('id_Vals_KPIs', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date_deb_Val_KPI', models.DateTimeField(auto_now_add=True, null=True)),
                ('Date_fin_Val_KPI', models.DateTimeField(blank=True, null=True)),
                ('Valeur_KPI', models.IntegerField(blank=True, null=True)),
                ('Commentaires_Val_KPI', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['Commentaires_Val_KPI'],
            },
        ),
        migrations.CreateModel(
            name='KPIs',
            fields=[
                ('id_KPI', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Code_KPI', models.IntegerField(blank=True, null=True)),
                ('Designation_KPI', models.CharField(blank=True, max_length=200, null=True)),
                ('Frequence_Calcul_KPI', models.CharField(blank=True, max_length=20, null=True)),
                ('Methode_Calcul_KPI', models.CharField(blank=True, max_length=200, null=True)),
                ('id_Decisions_Amelioration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.decisions_amelioration')),
                ('id_Vals_KPIs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.vals_kpis')),
            ],
            options={
                'ordering': ['Designation_KPI'],
            },
        ),
    ]
