# Generated by Django 3.1.6 on 2021-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0034_decisions_amelioration_kpis_vals_kpis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpis',
            name='id_Decisions_Amelioration',
        ),
        migrations.RemoveField(
            model_name='kpis',
            name='id_Vals_KPIs',
        ),
        migrations.DeleteModel(
            name='Decisions_Amelioration',
        ),
        migrations.DeleteModel(
            name='KPIs',
        ),
        migrations.DeleteModel(
            name='Vals_KPIs',
        ),
    ]
