# Generated by Django 3.1.6 on 2021-05-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0036_decisions_amelioration_kpi_vals_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='Id_Etat_Intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.etat_intervention'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='Id_Outillage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.outillages'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='Id_Personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.personnel_maintenance'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='Id_Type_Intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.type_intervention'),
        ),
    ]
